# Generated by Django 3.2.19 on 2023-09-11 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0004_remove_smstemplates_dlt_te_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslogs',
            name='sended_to',
            field=models.CharField(db_column='sended_to', max_length=50, validators=[django.core.validators.RegexValidator(message='mobile_no number must be between 4 and 11 digits.', regex='^\\d{4,11}$')]),
        ),
    ]
