# Generated by Django 3.2.19 on 2023-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0005_alter_smslogs_sended_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplates',
            name='dlt_te_id',
            field=models.CharField(db_column='dtl_te_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smslogs',
            name='to_be_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
