# Generated by Django 3.2.19 on 2023-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0006_auto_20230911_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslogs',
            name='dlt_te_id',
            field=models.CharField(db_column='dtl_te_id', max_length=100, null=True),
        ),
    ]
