# Generated by Django 3.2.19 on 2023-10-23 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0005_auto_20231022_2045'),
        ('message_log', '0007_alter_smslogs_dlt_te_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslogs',
            name='url_shortner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='url_shortner.urlshortners'),
        ),
    ]
