# Generated by Django 3.2.19 on 2023-10-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0008_smslogs_url_shortner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplates',
            name='dlt_te_id',
            field=models.CharField(db_column='dlt_te_id', max_length=100, null=True),
        ),
    ]
