# Generated by Django 3.2.19 on 2023-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0009_alter_smstemplates_dlt_te_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslogs',
            name='is_update',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
