# Generated by Django 3.2.19 on 2023-11-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0011_auto_20231026_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslogs',
            name='campaign_trigger',
        ),
        migrations.RemoveField(
            model_name='smslogs',
            name='campaign_trigger_history',
        ),
    ]
