# Generated by Django 3.2.19 on 2023-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringmanagers',
            name='calendar',
        ),
        migrations.AddField(
            model_name='hiringmanagers',
            name='calender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
