# Generated by Django 3.2.19 on 2023-11-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_manager', '0002_auto_20231124_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiringmanagers',
            old_name='calender',
            new_name='calendar',
        ),
    ]
