# Generated by Django 3.2.19 on 2023-11-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_manager', '0003_rename_calender_hiringmanagers_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringmanagers',
            name='off_day',
            field=models.BigIntegerField(null=True),
        ),
    ]
