# Generated by Django 3.2.19 on 2023-11-27 09:56

from django.db import migrations, models
import hiring_manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_manager', '0005_auto_20231127_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringmanagers',
            name='off_days',
            field=models.CharField(max_length=100, null=True, validators=[hiring_manager.validators.OffDaysValidator()]),
        ),
    ]
