# Generated by Django 3.2.19 on 2023-11-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidatenotes'),
        ('application', '0004_auto_20230811_1303'),
        ('hiring_manager', '0006_alter_hiringmanagers_off_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringmanagers',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application'),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='available_end_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='available_start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='calendar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='is_deleted',
            field=models.BooleanField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails'),
        ),
    ]
