# Generated by Django 3.2.19 on 2023-11-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20231017_1956'),
        ('application', '0004_auto_20230811_1303'),
        ('hiring_manager', '0007_auto_20231129_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringmanagers',
            name='calendar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='platform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='hiringmanagers',
            unique_together={('email', 'mobile', 'application_id')},
        ),
    ]
