# Generated by Django 3.2.19 on 2023-11-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_manager', '0008_auto_20231129_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringmanagers',
            name='available_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='available_start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hiringmanagers',
            name='off_days',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
