# Generated by Django 3.2.19 on 2023-12-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_manager', '0007_alter_hiringmanagers_is_deleted'),
        ('hiring_manager', '0009_auto_20231130_1730'),
    ]

    operations = [
    ]
