# Generated by Django 3.2.19 on 2023-06-23 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('minimum_experience', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Experience must be in format: 0-99 or 0.0-99.99', regex='^\\d{1,2}(\\.\\d{1,2})?$')])),
                ('maximum_experience', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Experience must be in format: 0-99 or 0.0-99.99', regex='^\\d{1,2}(\\.\\d{1,2})?$')])),
                ('minimum_salary', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Salary must be in format: 0-999,999.99', regex='^\\d{1,3}(,\\d{3})*(\\.\\d{1,2})?$')])),
                ('maximum_salary', models.IntegerField(validators=[django.core.validators.RegexValidator(message='Salary must be in format: 0-999,999.99', regex='^\\d{1,3}(,\\d{3})*(\\.\\d{1,2})?$')])),
                ('number_of_opening', models.IntegerField()),
                ('is_referral', models.BooleanField(default=False)),
                ('referral_bonus', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_visible_on_app', models.BooleanField(default=False)),
                ('visible_start_date', models.DateTimeField(blank=True, null=True)),
                ('visible_end_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('creater', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_details',
                'managed': True,
            },
        ),
    ]
