# Generated by Django 3.2.19 on 2023-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_functionalareas_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionalareas',
            name='code',
            field=models.CharField(max_length=8),
        ),
    ]
