# Generated by Django 3.2.19 on 2023-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_internationallocations_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewjob',
            name='maximum_salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addnewjob',
            name='minimum_salary',
            field=models.IntegerField(),
        ),
    ]
