# Generated by Django 3.2.19 on 2023-06-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20230630_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewjob',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
