# Generated by Django 3.2.19 on 2023-06-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_addnewjob_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewjob',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
