# Generated by Django 3.2.19 on 2023-06-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_addnewjob_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewjob',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
