# Generated by Django 3.2.19 on 2023-06-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_addnewjob_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewjob',
            name='first_skill',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='keyskills',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='second_skill',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='third_skill',
            field=models.CharField(default='', max_length=150),
        ),
    ]
