# Generated by Django 3.2.19 on 2023-08-09 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_appname_mail_sms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0011_auto_20230701_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUnderRecruiters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_start', models.DateTimeField(blank=True, null=True)),
                ('assign_end', models.DateTimeField(blank=True, null=True)),
                ('is_unassigned', models.BooleanField()),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobId', to='jobs.addnewjob')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recruiterId', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_under_recruiters',
                'managed': True,
            },
        ),
    ]
