# Generated by Django 3.2.19 on 2023-08-11 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_appname_mail_sms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0006_alter_candidatedetails_country_code'),
        ('candidate_status', '0001_initial'),
        ('jobs', '0012_jobunderrecruiters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_id', to='candidate.candidatedetails')),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='jobs.addnewjob')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate_status.candidatestatus')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'add_to_jobs',
                'managed': True,
            },
        ),
    ]
