# Generated by Django 3.2.19 on 2023-08-11 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20230811_1303'),
        ('jobs', '0013_addtojob'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_job_id', to='jobs.addnewjob')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag_recruiter_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_tags',
                'managed': True,
            },
        ),
    ]
