# Generated by Django 3.2.19 on 2023-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobtag_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobunderrecruiters',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
