# Generated by Django 3.2.19 on 2023-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20230811_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtojob',
            name='is_referred',
            field=models.BooleanField(default=False),
        ),
    ]
