# Generated by Django 3.2.19 on 2023-08-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidatenotes'),
        ('candidate_status', '0006_auto_20230822_1319'),
        ('referer', '0001_initial'),
        ('application', '0004_auto_20230811_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0020_addtojob_referer_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtojob',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='referer.referrer'),
        ),
        migrations.CreateModel(
            name='JobCandidateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_interview', models.BooleanField(default=False)),
                ('reminder_date', models.DateField()),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('atj', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='JobCandidateHistory_atj_id', to='jobs.addtojob')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='JobCandidateHistory_candidate_id', to='candidate.candidatedetails')),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='JobCandidateHistory_job_id', to='jobs.addnewjob')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate_status.candidatestatus')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='JobCandidateHistory_recruiter_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_candidate_histories',
                'managed': True,
            },
        ),
    ]
