# Generated by Django 3.2.19 on 2023-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_rename_referer_payment_status_addtojob_referer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcandidatehistory',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
