# Generated by Django 3.2.19 on 2023-08-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_alter_jobcandidatehistory_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcandidatehistory',
            name='is_deleted',
        ),
    ]
