# Generated by Django 3.2.19 on 2023-09-02 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaignchannel_channel_root_name'),
        ('jobs', '0025_remove_jobcandidatehistory_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtojob',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='addtojob',
            name='campaign_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaignevent'),
        ),
        migrations.AddField(
            model_name='addtojob',
            name='campaign_status',
            field=models.IntegerField(default=1),
        ),
    ]
