# Generated by Django 3.2.19 on 2023-09-03 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_addtojob_campaign_run_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtojob',
            name='campaign_run_time',
        ),
    ]
