# Generated by Django 3.2.19 on 2023-09-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_remove_addtojob_campaign_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtojob',
            name='campaign_run_time',
            field=models.DateTimeField(default='2023-09-05 02:35:00'),
        ),
    ]
