# Generated by Django 3.2.19 on 2023-10-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_addtojob_campaign_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtojob',
            name='campaign_status',
            field=models.IntegerField(default=0),
        ),
    ]
