# Generated by Django 3.2.19 on 2023-10-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_alter_addtojob_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewjob',
            name='auto_Integration',
            field=models.CharField(default='No', max_length=45),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='event_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='hiring_manager_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='interview_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='interview_within',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addnewjob',
            name='min_rating',
            field=models.IntegerField(default=0),
        ),
    ]
