# Generated by Django 3.2.19 on 2023-12-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_auto_20231031_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtojob',
            name='uploadedFile',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
