# Generated by Django 3.2.19 on 2023-12-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_addtojob_uploadedfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtojob',
            old_name='uploadedFile',
            new_name='attachment',
        ),
        migrations.AddField(
            model_name='addtojob',
            name='attachmentsFolder',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
