# Generated by Django 3.2.19 on 2023-12-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_remove_addtojob_attachmentsfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcandidatehistory',
            name='attachment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
