# Generated by Django 3.2.19 on 2023-10-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplates',
            name='dlt_te_id',
        ),
    ]
