# Generated by Django 3.2.19 on 2023-10-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0002_remove_emailtemplates_dlt_te_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplates',
            name='template_type',
        ),
    ]
