# Generated by Django 3.2.19 on 2023-10-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0005_emailtemplates_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailslogs',
            name='attachment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emailslogs',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailslogs',
            name='sended_bcc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emailslogs',
            name='sended_cc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='emailslogs',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
