# Generated by Django 3.2.19 on 2023-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0007_alter_emailslogs_to_be_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailslogs',
            name='sender_name',
            field=models.CharField(db_column='sender_name', default='Bot Shreyasi', max_length=50),
        ),
    ]
