# Generated by Django 3.2.19 on 2023-10-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0008_emailslogs_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailslogs',
            name='is_update',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
