# Generated by Django 3.2.19 on 2023-11-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0011_remove_emailslogs_url_shortner'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailslogs',
            name='is_smtp',
            field=models.BooleanField(default=False),
        ),
    ]
