# Generated by Django 3.2.19 on 2023-12-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0013_auto_20231128_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailslogs',
            name='attachments_folder',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
