# Generated by Django 3.2.19 on 2023-12-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0014_emailslogs_attachments_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailslogs',
            name='attachments_folder',
        ),
    ]
