# Generated by Django 3.2.19 on 2023-08-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20230826_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevent',
            name='color',
            field=models.CharField(default='#388E3C', max_length=25),
        ),
    ]
