# Generated by Django 3.2.19 on 2023-08-25 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaignevent_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignevent',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaignchannel'),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='trigger_interval_unit',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='campaignevent',
            name='trigger_mode',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
