# Generated by Django 3.2.19 on 2023-08-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20230826_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='trigger_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
