# Generated by Django 3.2.19 on 2023-09-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_alter_campaignevent_trigger_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevent',
            name='temp_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
