# Generated by Django 3.2.19 on 2023-09-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_campaignevent_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
