# Generated by Django 3.2.19 on 2023-09-02 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_alter_campaignevent_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignevent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_id', to='campaign.campaignevent'),
        ),
    ]
