# Generated by Django 3.2.19 on 2023-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_campaignevent_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignchannel',
            name='channel_root_name',
            field=models.CharField(default=models.CharField(max_length=45), max_length=45),
        ),
    ]
