# Generated by Django 3.2.19 on 2023-10-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaignchannel_channel_root_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevent',
            name='bot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='email_template',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='flow_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='sms_template',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
