# Generated by Django 3.2.19 on 2023-10-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20231023_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevent',
            name='flow_up_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
