# Generated by Django 3.2.19 on 2023-10-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0012_campaignevent_flow_up_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignevent',
            old_name='bot',
            new_name='bot_id',
        ),
        migrations.RenameField(
            model_name='campaignevent',
            old_name='email_template',
            new_name='email_template_id',
        ),
        migrations.RenameField(
            model_name='campaignevent',
            old_name='sms_template',
            new_name='sms_template_id',
        ),
    ]
