# Generated by Django 3.2.19 on 2023-10-22 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import url_shortner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0007_candidatenotes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20230811_1303'),
        ('message_logs', '0007_messagelogs_message_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=45)),
                ('old_url', models.CharField(max_length=100)),
                ('url_key', models.CharField(default=url_shortner.models.generate_random_uid, max_length=6, unique=True)),
                ('link_invalid', models.BooleanField(default=False)),
                ('url_opened', models.BooleanField(default=False)),
                ('url_opened_time', models.DateTimeField()),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails')),
                ('message_log', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='message_logs.messagelogs')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'url_shortners',
                'managed': True,
            },
        ),
    ]
