# Generated by Django 3.2.19 on 2023-10-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortners',
            name='chat_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
