# Generated by Django 3.2.19 on 2023-10-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_urlshortners_chat_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshortners',
            name='message_log',
        ),
    ]
