# Generated by Django 3.2.19 on 2023-10-22 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaignchannel_channel_root_name'),
        ('campaign_trigger', '0023_triggeractioncampaign_call_type'),
        ('url_shortner', '0004_auto_20231022_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortners',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='urlshortners',
            name='campaign_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_trigger.triggeractioncampaign'),
        ),
    ]
