# Generated by Django 3.2.19 on 2023-10-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0005_auto_20231022_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortners',
            old_name='campaign_trigger',
            new_name='campaign_trigger_history',
        ),
    ]
