# Generated by Django 3.2.19 on 2023-10-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0006_rename_campaign_trigger_urlshortners_campaign_trigger_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortners',
            name='url_for',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
