# Generated by Django 3.2.19 on 2023-10-25 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0011_remove_emailslogs_url_shortner'),
        ('message_log', '0011_auto_20231026_0321'),
        ('url_shortner', '0007_urlshortners_url_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortners',
            name='email_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_log.emailslogs'),
        ),
        migrations.AddField(
            model_name='urlshortners',
            name='sms_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message_log.smslogs'),
        ),
    ]
