# Generated by Django 3.2.19 on 2023-08-22 18:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('is_mobile_confirmed', models.BooleanField(default=False)),
                ('is_internal_referrer', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default='.', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField(null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.CharField(default='1', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be between 3 and 15 digits.', regex='^\\d{3,15}$')])),
                ('dob', models.DateField(default='2022-08-12')),
                ('short_name', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'referrers',
                'managed': True,
            },
        ),
    ]
