# Generated by Django 3.2.19 on 2023-10-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_id', models.CharField(blank=True, max_length=45, null=True)),
                ('call_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('chat_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_id', models.IntegerField(blank=True, null=True)),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('recruiter_id', models.IntegerField(blank=True, null=True)),
                ('candidate_id', models.IntegerField()),
                ('repetition', models.IntegerField(blank=True, null=True)),
                ('question', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.TextField(blank=True, null=True)),
                ('last_question', models.TextField(blank=True, null=True)),
                ('custom_data', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('disconnect_data', models.TextField(blank=True, null=True)),
                ('is_completed', models.IntegerField(blank=True, null=True)),
                ('is_sync', models.IntegerField(blank=True, null=True)),
                ('call_credit', models.IntegerField(blank=True, null=True)),
                ('is_processed', models.IntegerField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('latter', models.DateTimeField(blank=True, null=True)),
                ('hangup', models.CharField(blank=True, max_length=45, null=True)),
                ('interview', models.CharField(blank=True, max_length=45, null=True)),
                ('islater', models.IntegerField(blank=True, null=True)),
                ('video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('disposition', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_to_text', models.TextField(blank=True, null=True)),
                ('chat_rating', models.CharField(blank=True, max_length=45, null=True)),
                ('video_link2', models.CharField(blank=True, max_length=500, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gram_check_text', models.TextField(blank=True, null=True)),
                ('gram_check_perc', models.FloatField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('gram_check_text_2', models.TextField(blank=True, null=True)),
                ('gram_check_perc2', models.FloatField(blank=True, null=True)),
                ('skill1', models.IntegerField(blank=True, null=True)),
                ('skill2', models.IntegerField(blank=True, null=True)),
                ('skill3', models.IntegerField(blank=True, null=True)),
                ('chat_conv_done', models.IntegerField(blank=True, null=True)),
                ('device_name', models.CharField(blank=True, max_length=45, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=4500, null=True)),
                ('tab_opened', models.IntegerField(blank=True, null=True)),
                ('link_opened', models.IntegerField(blank=True, null=True)),
                ('target_months', models.IntegerField(blank=True, null=True)),
                ('link_open_count', models.IntegerField(blank=True, null=True)),
                ('chat_start_time', models.DateTimeField(blank=True, null=True)),
                ('chat_end_time', models.DateTimeField(blank=True, null=True)),
                ('sms_link_open_count', models.IntegerField(blank=True, null=True)),
                ('email_link_open_count', models.IntegerField(blank=True, null=True)),
                ('chat_link_open_time', models.DateTimeField(blank=True, null=True)),
                ('completedbychat', models.CharField(blank=True, db_column='CompletedByChat', max_length=15, null=True)),
                ('refresh_count', models.IntegerField(blank=True, null=True)),
                ('other_slots', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'chats',
                'managed': True,
            },
        ),
    ]
