# Generated by Django 3.2.19 on 2023-10-24 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
