# Generated by Django 3.2.19 on 2023-11-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0025_alter_callshistories_custom_data'),
        ('chat', '0004_chats_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='call_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='call.callshistories'),
        ),
    ]
