# Generated by Django 3.2.19 on 2023-07-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appname_mail_sms',
        ),
    ]
