# Generated by Django 3.2.19 on 2023-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genders',
                'managed': True,
            },
        ),
    ]
