# Generated by Django 3.2.19 on 2023-08-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0007_candidatenotes'),
        ('referer', '0001_initial'),
        ('application', '0004_auto_20230811_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0021_auto_20230823_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyRefers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_action_token', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('reference_mobile_no', models.CharField(max_length=15)),
                ('reference_email', models.CharField(max_length=100)),
                ('reference_name', models.CharField(max_length=100)),
                ('skill_selected', models.CharField(max_length=255)),
                ('linkdin_url', models.CharField(max_length=100)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails')),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.addnewjob')),
                ('referrer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referer.referrer')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'my_refers',
                'managed': True,
            },
        ),
    ]
