# Generated by Django 3.2.19 on 2023-07-19 22:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0005_candidatedetails_is_deleted'),
        ('application', '0002_remove_application_appname_mail_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message="Country code must be in the format '+123'.", regex='^\\+\\d{1,3}$')])),
                ('mobile_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='mobile_no number must be between 4 and 11 digits.', regex='^\\d{4,11}$')])),
                ('call_status', models.CharField(default='tocall', max_length=50)),
                ('candidate_status', models.CharField(default='No Status', max_length=50)),
                ('call_lanuaguage', models.CharField(default='en-IN-NeerjaNeural', max_length=50)),
                ('custom_data', models.JSONField()),
                ('conversation', models.TextField()),
                ('last_question', models.TextField()),
                ('call_start_time', models.DateTimeField()),
                ('call_end_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('call_duration', models.FloatField()),
                ('to_send_jd', models.BooleanField(default=False)),
                ('interview_time_start', models.DateTimeField()),
                ('interview_time_end', models.DateTimeField()),
                ('gram_check_text', models.TextField()),
                ('gram_check_text_2', models.TextField()),
                ('gram_check_perc', models.FloatField()),
                ('gram_check_perc_2', models.FloatField()),
                ('grammer_avg_rating', models.FloatField()),
                ('skill_1', models.FloatField()),
                ('skill_2', models.FloatField()),
                ('skill_3', models.FloatField()),
                ('skill_avg_rating', models.BooleanField(default=False)),
                ('grammer_interview_audio_link1', models.CharField(max_length=500)),
                ('grammer_interview_audio_link2', models.CharField(max_length=500)),
                ('is_validate_conversation', models.BooleanField(default=False)),
                ('call_to', models.CharField(max_length=50)),
                ('is_later', models.BooleanField(default=False)),
                ('inbound_lead', models.BooleanField(default=False)),
                ('type_of_call', models.CharField(default='OUTGOING', max_length=50)),
                ('call_credit', models.CharField(max_length=50)),
                ('call_initiate_id', models.CharField(max_length=50)),
                ('is_data_update', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails')),
            ],
            options={
                'db_table': 'call_logs',
                'managed': True,
            },
        ),
    ]
