# Generated by Django 3.2.19 on 2023-07-19 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate_status', '0001_initial'),
        ('jobs', '0011_auto_20230701_0032'),
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='candidate_status_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_status_id', to='candidate_status.candidatestatus'),
        ),
        migrations.AddField(
            model_name='calls',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.addnewjob'),
        ),
        migrations.AddField(
            model_name='calls',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
