# Generated by Django 3.2.19 on 2023-07-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='call_credit',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='calls',
            name='call_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='call_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='call_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='call_to',
            field=models.CharField(default='sipcall', max_length=50),
        ),
        migrations.AlterField(
            model_name='calls',
            name='conversation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='gram_check_perc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='gram_check_perc_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='gram_check_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='gram_check_text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='grammer_avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='grammer_interview_audio_link1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='grammer_interview_audio_link2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='interview_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='interview_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='last_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='skill_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='skill_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='skill_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
