# Generated by Django 3.2.19 on 2023-07-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_auto_20230720_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='candidate_status_id',
        ),
    ]
