# Generated by Django 3.2.19 on 2023-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_remove_calls_candidate_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='call_initiate_id',
            field=models.CharField(default=120, max_length=50),
        ),
    ]
