# Generated by Django 3.2.19 on 2023-07-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0005_alter_calls_call_initiate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='call_status',
            field=models.CharField(default='sipcall', max_length=50),
        ),
        migrations.AlterField(
            model_name='calls',
            name='call_to',
            field=models.CharField(default='bot7', max_length=50),
        ),
    ]
