# Generated by Django 3.2.19 on 2023-07-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0006_auto_20230720_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='call_initiate_id',
            field=models.CharField(default=54120, max_length=50),
        ),
    ]
