# Generated by Django 3.2.19 on 2023-07-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0007_alter_calls_call_initiate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='call_lanuaguage',
            new_name='call_language',
        ),
    ]
