# Generated by Django 3.2.19 on 2023-09-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0008_rename_call_lanuaguage_calls_call_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='call.calls'),
        ),
    ]
