# Generated by Django 3.2.19 on 2023-10-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0009_calls_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-01-01 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
