# Generated by Django 3.2.19 on 2023-10-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0016_triggeractioncampaign_is_ready_to_next_event'),
        ('call', '0010_auto_20231010_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='campaign_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_trigger.triggeractioncampaign'),
        ),
    ]
