# Generated by Django 3.2.19 on 2023-10-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_status', '0009_auto_20230911_1659'),
        ('call', '0011_calls_campaign_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='bot_status',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='candidate_status.candidatestatus'),
        ),
    ]
