# Generated by Django 3.2.19 on 2023-10-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0012_calls_bot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='candidate_status',
            new_name='disposition',
        ),
    ]
