# Generated by Django 3.2.19 on 2023-10-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0013_rename_candidate_status_calls_disposition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calls',
            table='calls',
        ),
    ]
