# Generated by Django 3.2.19 on 2023-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0014_alter_calls_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='is_update',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
