# Generated by Django 3.2.19 on 2023-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0015_calls_is_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='is_later',
            new_name='islater',
        ),
        migrations.AddField(
            model_name='calls',
            name='later',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
