# Generated by Django 3.2.19 on 2023-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0017_rename_later_calls_latter'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='other_slots',
            field=models.TextField(blank=True, null=True),
        ),
    ]
