# Generated by Django 3.2.19 on 2023-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0021_callshistories'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='call_history_id',
            field=models.IntegerField(default=1),
        ),
    ]
