# Generated by Django 3.2.19 on 2023-11-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0024_callshistories_campaign_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callshistories',
            name='custom_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
