# Generated by Django 3.2.19 on 2023-06-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='ip_address',
            field=models.CharField(blank=True, db_column='ip_address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rolepermissions',
            name='ip_address',
            field=models.CharField(blank=True, db_column='ip_address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='ip_address',
            field=models.CharField(blank=True, db_column='ip_address', max_length=45, null=True),
        ),
    ]
