# Generated by Django 3.2.19 on 2023-11-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0002_auto_20230701_0337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolepermissions',
            unique_together={('role', 'permission')},
        ),
    ]
