# Generated by Django 3.2.19 on 2023-12-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0003_alter_rolepermissions_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='slug',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
