# Generated by Django 3.2.19 on 2023-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0004_alter_permissions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together={('areas', 'slug')},
        ),
    ]
