# Generated by Django 3.2.19 on 2023-12-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0005_auto_20231201_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together=set(),
        ),
    ]
