# Generated by Django 3.2.19 on 2023-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0006_auto_20231201_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
