# Generated by Django 3.2.19 on 2023-12-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolepermission', '0007_alter_permissions_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissions',
            unique_together={('slug', 'areas_id')},
        ),
    ]
