# Generated by Django 3.2.19 on 2023-07-03 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0002_alter_candidatedetails_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'message_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessageUnsubscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'db_table': 'email_unsubscribers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessageLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(db_column='message_type', max_length=50)),
                ('sended_by', models.EmailField(db_column='sended_by', max_length=50)),
                ('is_send', models.IntegerField(db_column='is_send', default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField()),
                ('sended_to', models.EmailField(db_column='sended_to', max_length=50)),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=255)),
                ('attachment', models.CharField(max_length=500)),
                ('sended_cc', models.CharField(max_length=500)),
                ('sended_bcc', models.CharField(max_length=500)),
                ('sent_date', models.DateTimeField()),
                ('to_be_sent_date', models.DateTimeField()),
                ('is_otp', models.IntegerField()),
                ('dlt_te_id', models.CharField(db_column='dtl_te_id', max_length=100)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(db_column='added_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_message_log', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='application_message_log', to='application.application')),
                ('candidate_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails')),
            ],
            options={
                'db_table': 'message_logs',
                'managed': True,
            },
        ),
    ]
