# Generated by Django 3.2.19 on 2023-07-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogs',
            name='read_at',
            field=models.DateTimeField(default=''),
        ),
    ]
