# Generated by Django 3.2.19 on 2023-07-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_logs', '0003_auto_20230706_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogs',
            name='is_send',
            field=models.IntegerField(default=0),
        ),
    ]
