# Generated by Django 3.2.19 on 2023-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_logs', '0004_alter_messagelogs_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogs',
            name='sended_by',
            field=models.CharField(db_column='sender_name', default='Bot Shreyasi', max_length=50),
        ),
    ]
