# Generated by Django 3.2.19 on 2023-07-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_logs', '0005_alter_messagelogs_sended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelogs',
            name='sended_by',
            field=models.CharField(db_column='sended_by', default='noreply', max_length=50),
        ),
    ]
