# Generated by Django 3.2.19 on 2023-07-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_tempelate', '0004_auto_20230706_0207'),
        ('message_logs', '0006_alter_messagelogs_sended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelogs',
            name='message_template',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='message_tempelate.messagetemplates'),
        ),
    ]
