# Generated by Django 3.2.19 on 2023-07-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_remove_application_appname_mail_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('root_name', models.CharField(max_length=255)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'db_table': 'candidate_statuses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CandidateStatusRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('candidate_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_status', to='candidate_status.candidatestatus')),
                ('candidate_status_child', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_status_child', to='candidate_status.candidatestatus')),
            ],
            options={
                'db_table': 'candidate_statuses_relations',
                'managed': True,
            },
        ),
    ]
