# Generated by Django 3.2.19 on 2023-08-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatusrelations',
            name='candidate_status',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RefererPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_status', to='candidate_status.candidatestatus')),
            ],
            options={
                'db_table': 'referer_payment_statuses',
                'managed': True,
            },
        ),
    ]
