# Generated by Django 3.2.19 on 2023-08-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_status', '0002_auto_20230821_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatusrelations',
            name='candidate_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_status', to='candidate_status.candidatestatus'),
        ),
        migrations.AlterField(
            model_name='refererpaymentstatus',
            name='status_name',
            field=models.CharField(max_length=100),
        ),
    ]
