# Generated by Django 3.2.19 on 2023-08-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_tempelate', '0004_auto_20230706_0207'),
        ('candidate_status', '0005_refererpaymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatus',
            name='candidate_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_email_template_id', to='message_tempelate.messagetemplates'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='candidate_sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_sms_template_id', to='message_tempelate.messagetemplates'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='is_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='refer_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refer_status', to='candidate_status.refererpaymentstatus'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='referer_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_email_template_id', to='message_tempelate.messagetemplates'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='referer_sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_sms_template_id', to='message_tempelate.messagetemplates'),
        ),
    ]
