# Generated by Django 3.2.19 on 2023-09-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_log', '0004_remove_smstemplates_dlt_te_id'),
        ('email_log', '0001_initial'),
        ('candidate_status', '0008_alter_candidatestatus_referer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatestatus',
            name='candidate_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_email_template_id', to='email_log.emailtemplates'),
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='candidate_sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_sms_template_id', to='message_log.smstemplates'),
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='referer_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_email_template_id', to='email_log.emailtemplates'),
        ),
        migrations.AlterField(
            model_name='candidatestatus',
            name='referer_sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_sms_template_id', to='message_log.smstemplates'),
        ),
    ]
