# Generated by Django 3.2.19 on 2023-11-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_log', '0013_auto_20231128_1656'),
        ('message_log', '0012_auto_20231128_1656'),
        ('candidate_status', '0010_auto_20231023_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatus',
            name='candidate_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_email_template_id', to='email_log.emailtemplates'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='candidate_sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_sms_template_id', to='message_log.smstemplates'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='referer_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_email_template_id', to='email_log.emailtemplates'),
        ),
        migrations.AddField(
            model_name='candidatestatus',
            name='referer_sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referer_sms_template_id', to='message_log.smstemplates'),
        ),
    ]
