# Generated by Django 3.2.19 on 2023-06-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        ('history', '0002_history_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='application',
        ),
        migrations.RemoveField(
            model_name='history',
            name='source',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AlterField(
            model_name='history',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails'),
        ),
    ]
