# Generated by Django 3.2.19 on 2023-07-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smtpdetail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpdetails',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='smtpdetails',
            name='user_id',
        ),
        migrations.AddField(
            model_name='smtpdetails',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application'),
        ),
        migrations.AddField(
            model_name='smtpdetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smtpdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
