# Generated by Django 3.2.19 on 2023-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtpdetail', '0002_auto_20230701_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpdetails',
            name='is_smtp',
            field=models.BooleanField(default=False),
        ),
    ]
