# Generated by Django 3.2.19 on 2023-06-28 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be in the format: '+<country code>-<number>'.", regex='^\\+\\d{1,3}-\\d{3,15}$')]),
        ),
    ]
