# Generated by Django 3.2.19 on 2023-07-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidatedetails_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatedetails',
            old_name='full_name',
            new_name='candidate_name',
        ),
    ]
