# Generated by Django 3.2.19 on 2023-07-12 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '__first__'),
        ('candidate', '0003_rename_full_name_candidatedetails_candidate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatedetails',
            name='country_code',
            field=models.CharField(default=91, max_length=4, validators=[django.core.validators.RegexValidator(message="Country code must be in the format '+123'.", regex='^\\+\\d{1,3}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='mobile_no',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='mobile_no number must be between 4 and 11 digits.', regex='^\\d{4,11}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='candidatedetails',
            unique_together={('application', 'email', 'mobile_no')},
        ),
    ]
