# Generated by Django 3.2.19 on 2023-05-24 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.CharField(default='1', max_length=150, unique=True)),
                ('dob', models.DateField(default='2022-08-12')),
                ('manager', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
