# Generated by Django 3.2.19 on 2023-05-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rsa_salt',
            field=models.BinaryField(null=True),
        ),
    ]
