# Generated by Django 3.2.19 on 2023-05-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_rsa_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rsa_salt',
        ),
    ]
