# Generated by Django 3.2.19 on 2023-06-28 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20230627_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_no',
            field=models.CharField(default='1', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Mobile number must be in the format: '+<country code>-<number>'.", regex='^\\+\\d{1,3}-\\d{3,15}$')]),
        ),
    ]
