# Generated by Django 3.2.19 on 2023-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='forget_password_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_entry_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
