# Generated by Django 3.2.19 on 2023-12-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_auto_20231130_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_entry_attempts',
        ),
    ]
