# Generated by Django 3.2.19 on 2023-07-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_tempelate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetemplates',
            old_name='templatename',
            new_name='template_name',
        ),
        migrations.RemoveField(
            model_name='messagetemplates',
            name='title',
        ),
        migrations.AddField(
            model_name='messagetemplates',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagetemplates',
            name='dlt_te_id',
            field=models.CharField(blank=True, db_column='dtl_te_id', max_length=100, null=True),
        ),
    ]
