# Generated by Django 3.2.19 on 2023-07-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_tempelate', '0002_auto_20230704_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplates',
            name='template_type',
            field=models.CharField(db_column='template_type', max_length=50),
        ),
    ]
