# Generated by Django 3.2.19 on 2023-07-05 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_tempelate', '0003_alter_messagetemplates_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplates',
            name='sended_by',
            field=models.CharField(db_column='sended_by', default='passive', max_length=50),
        ),
        migrations.AddField(
            model_name='messagetemplates',
            name='sender_name',
            field=models.CharField(db_column='sender_name', default='Bot Shreyasi', max_length=50),
        ),
        migrations.CreateModel(
            name='EmailHeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_header', models.CharField(max_length=200)),
                ('email_footer', models.CharField(max_length=200)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(db_column='added_by', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_email_header_footer', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
            ],
            options={
                'db_table': 'email_headers_footers',
                'managed': True,
            },
        ),
    ]
