# Generated by Django 3.2.19 on 2023-06-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_name_department_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='client_or_department',
            field=models.CharField(default='department', max_length=20),
        ),
    ]
