# Generated by Django 3.2.19 on 2023-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='client_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
