# Generated by Django 3.2.19 on 2023-10-17 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0006_alter_department_head_of_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='client_or_department',
            field=models.CharField(choices=[('client', 'Client'), ('department', 'Department')], default='department', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to=settings.AUTH_USER_MODEL),
        ),
    ]
