# Generated by Django 3.2.19 on 2023-12-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0004_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='otp',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='attempt_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
