# Generated by Django 3.2.19 on 2023-12-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0005_auto_20231201_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='number_of_attempts',
        ),
    ]
