# Generated by Django 3.2.19 on 2023-10-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaignchannel_channel_root_name'),
        ('campaign_trigger', '0003_auto_20231007_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeractioncampaign',
            name='next_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_action_id', to='campaign.campaignevent'),
        ),
    ]
