# Generated by Django 3.2.19 on 2023-10-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaignchannel_channel_root_name'),
        ('campaign_trigger', '0005_alter_triggeractioncampaign_next_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeractioncampaign',
            name='next_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_action', to='campaign.campaignevent'),
        ),
    ]
