# Generated by Django 3.2.19 on 2023-10-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0007_alter_triggeractioncampaign_next_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeractioncampaign',
            name='next_action',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
