# Generated by Django 3.2.19 on 2023-10-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_alter_addtojob_campaign_status'),
        ('departments', '0004_department_is_deleted'),
        ('campaign_trigger', '0011_auto_20231009_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeractioncampaign',
            name='client_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='triggeractioncampaign',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.addnewjob'),
        ),
    ]
