# Generated by Django 3.2.19 on 2023-10-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0014_remove_triggeractioncampaign_is_ready_to_next_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triggeractioncampaign',
            old_name='status',
            new_name='candidate_status',
        ),
    ]
