# Generated by Django 3.2.19 on 2023-10-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20231017_1956'),
        ('campaign', '0010_campaignchannel_channel_root_name'),
        ('application', '0004_auto_20230811_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0036_alter_addtojob_campaign_status'),
        ('candidate_status', '0009_auto_20230911_1659'),
        ('candidate', '0007_candidatenotes'),
        ('campaign_trigger', '0018_alter_triggeractioncampaign_next_action_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerActionCampaignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('add_to_job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.addtojob')),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('campaign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign')),
                ('candidate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatedetails')),
                ('client_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('job', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.addnewjob')),
                ('status', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidate_status.candidatestatus')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_triggers_history',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='triggeractioncampaign',
            name='trigger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='campaign_trigger.triggeractioncampaignhistory'),
        ),
    ]
