# Generated by Django 3.2.19 on 2023-10-21 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidatenotes'),
        ('candidate_status', '0009_auto_20230911_1659'),
        ('jobs', '0036_alter_addtojob_campaign_status'),
        ('campaign', '0010_campaignchannel_channel_root_name'),
        ('departments', '0007_auto_20231017_1956'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20230811_1303'),
        ('campaign_trigger', '0019_auto_20231021_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TriggerActionCampaignHistory',
            new_name='ActionTrigger',
        ),
        migrations.AlterModelTable(
            name='actiontrigger',
            table='campaigns_triggers',
        ),
        migrations.AlterModelTable(
            name='triggeractioncampaign',
            table='campaign_triggers_history',
        ),
    ]
