# Generated by Django 3.2.19 on 2023-10-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0020_auto_20231021_1701'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actiontrigger',
            table='campaign_triggers',
        ),
    ]
