# Generated by Django 3.2.19 on 2023-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0021_alter_actiontrigger_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontrigger',
            name='later_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
