# Generated by Django 3.2.19 on 2023-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0022_actiontrigger_later_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeractioncampaign',
            name='call_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
