# Generated by Django 3.2.19 on 2023-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_trigger', '0023_triggeractioncampaign_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggeractioncampaign',
            name='action_temp_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
